ReportConfiguration:
  HideChapter:
    RiskRulesCheckedByThreagile: true
    TagListing: true
    SharedRuntimes: true
    AssetRegister: true
    RisksByTechnicalAsset: true
    DataBreachProbabilities: true
    STRIDEClassification: true
    AssignmentByFunction: true
    RAAAnalysis: true
    DataMapping: true
    ImpactRemainingRisks: true
HideEmptyChapters: true
AddLegend: true
TempFolder: tmp
AppFolder: .
DataFolder: output
PluginFolder: .
